FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    x11-apps \
    xauth \
    openjdk-17-jdk \
    && rm -rf /var/lib/apt/lists/*

COPY . .

ENV DISPLAY=host.docker.internal:0

CMD ["java", "-jar", "calc.jar"]